In [1]:
a: str = 'ADAM'
a = a.lower()
print(a)

adam


In [2]:
a = [1, 'a', 1, 3, 1, 'a']
a = a.index(3)
print(a)

3


In [1]:
import torch
a = torch.tensor([1j+2, 10j+20])
real = a.real
imag = a.imag
print(real)
print(imag)

tensor([ 2., 20.])
tensor([ 1., 10.])


In [2]:
import torch
a = torch.float16
print(str(a))

torch.float16


In [7]:
import torch

a = torch.zeros((3, 1))
b = torch.ones((3, 1))
c = torch.stack([a, b], dim=1)
print(c.shape)
print(c)

torch.Size([3, 2, 1])
tensor([[[0.],
         [1.]],

        [[0.],
         [1.]],

        [[0.],
         [1.]]])


In [1]:
a = None
b = ''
print(isinstance(a, str))
print(isinstance(b, str))

False
True


In [14]:
from typing import Tuple
a = tuple(['1', '2', 'm'])
b = type(a)

i = isinstance(a, Tuple)
print(i)
j = isinstance(a[0], str)
print(j)
k = isinstance(a, [Tuple][0])
print(k)

True
True
True


In [18]:
a = [2, 1]
c, _ = a
print(c)

2


In [1]:
import torch
a = torch.float32
print(isinstance(a, str))
print(isinstance(a, torch.dtype))

False
True


In [12]:
from typing import Tuple
a = tuple(['1', '2', 'm'])
a = ('k', )

print(type(a))
print(type(a[0]))
print(type(tuple([None])))
i = type(a)==type(tuple([None]))
print(i)
i = type(a)==type((83, ))
print(i)
i = type(a)==type((83, 'i'))
print(i)
j = type(a[0])==type((83, )[0])
print(j)
j = type(a[0])==type(('1', '3')[0])
print(j)

<class 'tuple'>
<class 'str'>
<class 'tuple'>
True
True
True
False
True


In [13]:
edge = (83, 83)
edge = (93, 93, 93)
print(edge)

(93, 93, 93)


In [3]:
a = ""
b = a==False
print(b)

False


In [3]:
import numpy as np 

a = [1, 3, 3, 1, 1, 1, 1]
a = np.array(a)
b = np.where(a==1)
c = np.where(a==1, -1*a, a)
print(b[0])
print(c)

[0 3 4 5 6]
[-1  3  3 -1 -1 -1 -1]


In [4]:
from numpy.typing import NDArray
import numpy as np 
atom_types = [2, 2, 2, 3, 3, 3, 0, 2, 3]
atom_types: NDArray = np.array(atom_types) # shape=(num_atoms, )
partial_index: NDArray = np.empty_like(atom_types) # shape=(num_atoms, )
for atomic_number in np.unique(atom_types):
    global_index: NDArray = np.where(atom_types==atomic_number)[0]
    partial_index[global_index] = np.arange(len(global_index))
print(partial_index)

[0 1 2 0 1 2 0 3 3]


In [2]:
a = None
b = [1]
print(a+b)

[1]


In [2]:
from e3nn.o3 import Irreps
a = Irreps("2x1o")
print(a*2)
a = str(a)
print(type(a))
print(a)

2x1o+2x1o
<class 'str'>
2x1o


In [1]:
def a(input: None):
    print(3)
a(None)

3


In [1]:
avg_aggregate_num = None
avg_aggregate_num: None | float = float(avg_aggregate_num) if avg_aggregate_num is not None else 0.0
print(avg_aggregate_num)

0.0


In [18]:
from e3nn.o3 import Irreps

a = Irreps("4x1o+8x0e+100x4e")
b = [mul for mul, ir in a]
c = [(int(mul/2), ir) for mul, ir in a]
print(c)
c = [Irreps(str(mul//2)+"x"+str(ir)) for mul, ir in a]
print(c)
d = Irreps("")
for i in c:
    d = d + i
print(d)
e = 100/3
print(e.is_integer())
e = 100/2
print(e.is_integer())

[(2, 1o), (4, 0e), (50, 4e)]
[2x1o, 4x0e, 50x4e]
2x1o+4x0e+50x4e
False
True


In [3]:
from e3nn.o3 import Irreps, Irrep
irreps_edges_carbon2oxygen: Irreps = Irreps("16x0e")
irreps_edges_oxygen2carbon: Irreps = Irreps("16x0e+8x1e+4x2e")
irreps_edge_dict = {"6-8": irreps_edges_carbon2oxygen, "8-6": irreps_edges_oxygen2carbon}
for v in irreps_edge_dict.values():
    for mul, ir in v: 
        print(ir)
        print(type(ir))
        assert ir == Irrep("0e")
        # assert ir == Irreps("0e")

0e
<class 'e3nn.o3._irreps.Irrep'>
0e
<class 'e3nn.o3._irreps.Irrep'>
1e
<class 'e3nn.o3._irreps.Irrep'>


AssertionError: 

In [2]:
from e3nn.o3 import Irreps
irreps_a: Irreps = Irreps("16x0e")
irreps_b: Irreps = Irreps("16x0e+8x1e+4x2e")
for i, (mul, ir) in enumerate(irreps_b):
    print(mul*ir.dim)

16
24
20


In [3]:
from e3nn.o3 import Irreps, Irrep
a = Irreps("16x0e+8x1e+4x2e")
print(Irrep("4e") in a)

False


In [7]:
import torch

a = torch.arange(0, 16).view(4, 4)
b = a[0]
d = (a==b).all(dim=1)
c = torch.zeros((2,))
print(c)
print(d)

tensor([0., 0.])
tensor([ True, False, False, False])


In [8]:
import torch
a = torch.arange(0, 12).view(3, 4)
b = a[0]
print(a/b)

tensor([[   nan, 1.0000, 1.0000, 1.0000],
        [   inf, 5.0000, 3.0000, 2.3333],
        [   inf, 9.0000, 5.0000, 3.6667]])


In [16]:
import torch

a = torch.arange(24).view(2, 3, 4)
b = (a==a[0])
while(b.dim()>=2):
    b = b.any(dim=-1).float()
print(b.dim())
print(b)

1
tensor([1., 0.])


In [22]:
import torch 
a = torch.arange(24)
a = a[None, 1:2]
print(a)
print(a.shape)

tensor([[1]])
torch.Size([1, 1])


In [6]:
import torch
a = torch.arange(24).view(2, 3, 4)
a = torch.arange(6).view(2, 3)
print(a)
b = a[0]
print(b)

a = torch.sum(a * b, dim=-1)
print(a)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 1, 2])
tensor([ 5, 14])


In [4]:
from e3nn.o3 import Irreps
a = Irreps("1x3e")
for mul, ir in a:
    print(mul)
    print(ir)

1
3e


In [6]:
from e3nn.o3 import Irreps
from typing import Dict

a = {1: Irreps("1x0e"), 2: 3}
b = {"3": 2}
print(all([type(a)==type(b) for _ in range(3)]))

True


In [2]:
import torch
a = torch.randn(1)
print(a)

tensor([2.2385])


In [8]:
import torch
m = torch.zeros((3, 3, 4))
a = torch.arange(12).view(3, 4)
b = a.view(a.shape[0], *[1 for _ in range(m.dim()-2)], a.shape[1])
print(a.shape)
print(b.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
